### ISSUE TITLE
Geth Header Broken Chain Ancestry & Sync failed, dropping peer

### ISSUE THREAD

**Issue by christiankiller** [blockchain-signaling-system/bloss-core#5]
Even though all nodes have internet access and correct ntp: 
Multiple times, geth seemingly random started to fail with
`Header broken chain ancestry` and `Synchronisation failed, dropping peer` after a certain amount of blocks.

**Comment by christiankiller** [comment]
After cleaning chaindata & lightchaindata, regenerating DAG;
 
this error keeps happening
```
Nov 18 16:06:16 controller400 geth[2818]: INFO [11-18|16:06:16] Generated ethash verification cache      epoch=1 elapsed=13.857s
Nov 18 16:06:16 controller400 geth[2818]: ERROR[11-18|16:06:16] Failed to generate mapped ethash dataset epoch=1 err="cannot allocate memory"
Nov 18 16:06:16 controller400 geth[2818]: runtime: out of memory: cannot allocate 2164260864-byte block (715161600 in use)
Nov 18 16:06:16 controller400 geth[2818]: fatal error: out of memory
Nov 18 16:06:16 controller400 geth[2818]: runtime stack:
Nov 18 16:06:16 controller400 geth[2818]: runtime.throw(0x970fc9, 0xd)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/panic.go:605 +0x70
Nov 18 16:06:16 controller400 geth[2818]: runtime.largeAlloc(0x80ffff00, 0x12b0101, 0xb28c2a88)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/malloc.go:829 +0xe4
Nov 18 16:06:16 controller400 geth[2818]: runtime.mallocgc.func1()
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/malloc.go:722 +0x38
Nov 18 16:06:16 controller400 geth[2818]: runtime.systemstack(0x1301ca80)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_arm.s:264 +0x80
Nov 18 16:06:16 controller400 geth[2818]: runtime.mstart()
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/proc.go:1135
Nov 18 16:06:16 controller400 geth[2818]: goroutine 2178 [running]:
Nov 18 16:06:16 controller400 geth[2818]: runtime.systemstack_switch()
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/asm_arm.s:209 +0x4 fp=0x13439d90 sp=0x13439d8c pc=0x7437c
Nov 18 16:06:16 controller400 geth[2818]: runtime.mallocgc(0x80ffff00, 0x87c950, 0x12a5a01, 0x545498)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/malloc.go:721 +0x6a8 fp=0x13439dec sp=0x13439d90 pc=0x2ca80
Nov 18 16:06:16 controller400 geth[2818]: runtime.makeslice(0x87c950, 0x203fffc0, 0x203fffc0, 0x17b51020, 0x2, 0x2)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/slice.go:54 +0x68 fp=0x13439e00 sp=0x13439dec pc=0x5ffc8
Nov 18 16:06:16 controller400 geth[2818]: runtime.makeslice64(0x87c950, 0x203fffc0, 0x0, 0x203fffc0, 0x0, 0x2, 0x0, 0x0)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/runtime/slice.go:69 +0x44 fp=0x13439e1c sp=0x13439e00 pc=0x60094
Nov 18 16:06:16 controller400 geth[2818]: github.com/ethereum/go-ethereum/consensus/ethash.(*dataset).generate.func1()
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:337 +0x6a8 fp=0x13439f98 sp=0x13439e1c pc=0x5454c0
Nov 18 16:06:16 controller400 geth[2818]: sync.(*Once).Do(0x131b6714, 0x1f4bbfbc)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/.gimme/versions/go1.9.4.linux.amd64/src/sync/once.go:44 +0xb8 fp=0x13439fb0 sp=0x13439f98 pc=0x8acc0
Nov 18 16:06:16 controller400 geth[2818]: github.com/ethereum/go-ethereum/consensus/ethash.(*dataset).generate(0x131b66f0, 0x1308df80, 0x16, 0x2, 0x131b6600)
Nov 18 16:06:16 controller400 geth[2818]:         /home/travis/gopath/src/github.com/ethereum/go-ethereum/consensus/ethash/ethash.go:292 +0x64 fp=0x13439fd4 sp=0x13439fb0 pc=0x540d48
Nov 18 16:06:16 controller400 systemd[1]: geth.service: Failed with result 'exit-code'
```

**Comment by christiankiller** [comment]
Fixed by starting geth with a little bit of delay between instances, 
e.g. AS400 `sudo systemctl start geth`; wait 4 seconds, start AS500, wait 4 seconds; start as600..
